services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: gs-user
      MONGO_INITDB_ROOT_PASSWORD: gs-password
    logging:
      driver: "none"
    volumes:
      - mongo-data:/data/db

  git-spect-server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8000:8000"
    env_file:
      - .env

volumes:
  mongo-data:
