services:
  elasticsearch:
    image: elasticsearch:8.13.4
    container_name: elasticsearch
    restart: always
    networks:
      - elk-stack
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
      - "discovery.type=single-node"
  
  kibana:
    image: kibana:8.13.4
    container_name: kibana
    restart: always
    depends_on:
      - elasticsearch
    networks:
      - elk-stack
    ports:
      - "5601:5601"
    environment:
      - "ELASTICSEARCH_URL=http://elasticsearch:9200"

  git-spect-dev-db:
    image: postgres:13
    restart: always
    container_name: git-spect-dev-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: git_spect
    volumes:
      - postgres-data:/data/db

  git-spect-server:
    depends_on:
      - git-spect-dev-db
      - elasticsearch
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    env_file:
      - .env.development

networks:
  elk-stack:
    name: elk-stack
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.1.0/24

volumes:
  postgres-data:
